project_id = "sdyichnqroitptxloyyl"

[functions.face-recognition]
verify_jwt = false

[functions.face-enroll]
verify_jwt = true

[functions.django-proxy]
verify_jwt = false

[functions.send-member-invite]
verify_jwt = true

[functions.send-admin-invite]
verify_jwt = true
